Algoritmo "funcao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/03/2023
Var
// Seção de Declarações das variáveis
num1, num2: inteiro

Inicio
  funcao somar(num1, num2: inteiro):inteiro
  var
  inicio
    retorne num1 + num2
  fimfuncao
  
escreva(somar(2,2))

Fimalgoritmo